server:
    port: 9090
    servlet:
        session:
            timeout: 20m
spring:
    application:
        name: admin-web
    session:
        redis:
            flush-mode: on_save
    profiles:
        group:
            "local": "core-local"
#    mvc:
#        pathmatch:
#            matching-strategy: ant_path_matcher # 2.6+ 에서 기본으로 권장 path_pattern_parser
    thymeleaf:
        cache: false
        check-template-location: true
        prefix: file:admin-web/src/main/resources/templates/
#        prefix: classpath:templates/ # prod 환경은 classpath 로 한다.
        suffix: .html
        enabled: true
    main:
        allow-bean-definition-overriding: true
    messages:
        basename: i18n/message
        fallback-to-system-locale: true
        encoding: UTF-8
    cloud:
        compatibility-verifier:
            enabled: false
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
logging:
    config: classpath:logback-spring.xml
---
server:
    port: 9090
    servlet:
        encoding:
            enabled: true
            charset: UTF-8
            force: true
        session:
            timeout: 20m
spring:
    config:
        activate:
            on-profile: local
    cloud:
        openfeign:
            client:
                config:
                    default:
                        connect-timeout: 1000
                        read-timeout: 3000
                    google:
                        url: "https://"
                        connect-timeout: 3000
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ""
                        client-secret: ""
                        redirect-uri: ""
                        scope:
                            - profile
                            - email
